#version: "3.8"
services:
  postgres:
    image: 'startalk/startalk-pg:0.1'
    #network_mode: host
    restart: always
    volumes:
      - ${PWD}/volume/data/pg/pgdata-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ejabberd
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  redis:
    #image: 'startalk/startalk-redis:0.1'
    #network_mode: host
    image: 'redis:6.0.9-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${PWD}/conf/redis/redis.conf:/usr/local/etc/redis/redis.conf


  openresty:
    #network_mode: host
    image: 'startalk/startalk-or:0.1'
    volumes:
      - ${PWD}/volume/log/or/:/usr/local/openresty/nginx/logs/
    ports:
      - '8080:8080'

  ejabberd:
    #network_mode: host
    image: 'startalk/startalk-ejab:0.1'
    ports:
      - '5202:5202'
      - '5280:5280'
    volumes:
      - ${PWD}/volume/log/ejabberd/:/startalk/ejabberd/var/log/ejabberd/
      - ${PWD}/conf/ejabberd/ejabberdctl.cfg.qunar:/startalk/ejabberd/etc/ejabberd/ejabberdctl.cfg
      - ${PWD}/conf/ejabberd/ejabberd.yml.qunar:/startalk/ejabberd/etc/ejabberd/ejabberd.yml
    command: /startalk/ejabberd/sbin/ejabberdctl foreground
    depends_on:
      - postgres
      - redis

  im_http_service:
    #network_mode: host
    image: 'startalk/startalk-im_http_service:0.1'
    ports:
      - '8081:8081'
    volumes:
      - ${PWD}/volume/log/im_http_service/:/usr/local/tomcat/logs/
      - ${PWD}/conf/im_http_service/server.xml:/usr/local/tomcat/conf/server.xml
      - ${PWD}/conf/im_http_service/classes/:/usr/local/tomcat/webapps/im_http_service/WEB-INF/classes/
    depends_on:
      - postgres
      - redis

  qfproxy:
    #network_mode: host
    image: 'startalk/startalk-qfproxy:0.1'
    ports:
      - '8082:8082'
    volumes:
      - ${PWD}/volume/log/qfproxy/:/usr/local/tomcat/logs/
      - ${PWD}/conf/qfproxy/server.xml:/usr/local/tomcat/conf/server.xml
      - ${PWD}/conf/qfproxy/classes/:/usr/local/tomcat/webapps/qfproxy/WEB-INF/classes/
    depends_on:
      - postgres
      - redis

  push_service:
    #network_mode: host
    image: 'startalk/startalk-push_service:0.1'
    ports:
      - '8083:8083'
    volumes:
      - ${PWD}/volume/log/push_service/:/usr/local/tomcat/logs/
      - ${PWD}/conf/push_service/server.xml:/usr/local/tomcat/conf/server.xml
      - ${PWD}/conf/push_service/classes/:/usr/local/tomcat/webapps/push_service/WEB-INF/classes/
    depends_on:
      - postgres
      - redis

  search:
    #network_mode: host
    image: 'startalk/startalk-search:0.1'
    volumes:
      - ${PWD}/volume/log/search/:/app/log/
    ports:
      - '8884:8884'
    depends_on:
      - postgres
      - redis

